version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: repair-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: ca2_submission
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./Updated Schema CA2.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data: